name: Set up Node
description: Set up Node

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Install root project node packages
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 30
        max_attempts: 3
        command: npm ci

    - name: Install node packages for desktop submodule
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 30
        max_attempts: 3
        command: cd desktop && npm ci
