name: John's Stats Testing

on:
  push:
    branches:
    - "**/*"

jobs:
  perf-tests:
    if: ${{ github.actor != 'OSBotify' }}
    runs-on: ubuntu-latest-reassure-tests
    steps:
      - name: Test sending some fake data to Graphite
        env:
          GRAPHITE_SERVER: ${{ vars.GRAPHITE_SERVER }}
          GRAPHITE_PORT: ${{ vars.GRAPHITE_PORT }}
        run: echo -e "reassure_testing.PR-0.[SelectionList]-should-render-multiple-selection-and-select-3-items.renderDuration 3000 1709229855" | nc -q0 "$GRAPHITE_SERVER" "$GRAPHITE_PORT"
